### ISSUE TITLE
Forge 1.20.1 Crash 

### ISSUE THREAD

**Issue by LaurentCoolen** [GenerationsMod/Generations-Core#28]
![Capture d'écran 2024-02-20 164816](https://github.com/GenerationsMod/Generations-Core/assets/160633511/e7a7fbec-6f88-4aed-80ac-a18ef9b28790)
Hello, I launch the game and it gives me this message

**Comment by LaurentCoolen** [comment]
[latest.log](https://github.com/GenerationsMod/Generations-Core/files/14348468/latest.log)

**Comment by JT122406** [comment]
noobanidus/mods/lootr/config/ConfigManager

**Comment by LaurentCoolen** [comment]
I don't have any Lootr mods

**Comment by JT122406** [comment]
Well it's not Gens

**Comment by LaurentCoolen** [comment]
It's what?

**Comment by JT122406** [comment]
Try removing Gens and rerunning see if it still crash

**Comment by JT122406** [comment]
wait a second

**Comment by JT122406** [comment]
found the issue it is us
@Waterpicker 
Failed to scan recipe generations_core:rks/artcovish. This should be reported to generations_core!
java.lang.RuntimeException: java.lang.NullPointerException: Parameter specified as non-null is null: method com.cobblemon.mod.common.item.PokemonItem$Companion.from, parameter species

**Comment by GuikiPT** [comment]
Also just for test, try to remove the xaero's map:
```
received server config settings
[16:57:08] [Render thread/INFO]: Received config from the server: 
[16:57:08] [Render thread/INFO]: Reloading entity icon resources...
[16:57:08] [Render thread/INFO]: Done!
[16:57:09] [Render thread/INFO]: Finalizing world map session...
[16:57:09] [Thread-7/ERROR]: Region failed to load: (2147483647) 0_0 L0 xaero.map.region.MapRegion@93815cd
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 129
	at it.unimi.dsi.fastutil.longs.Long2LongOpenHashMap.rehash(Long2LongOpenHashMap.java:1366) ~[fastutil-8.5.9.jar%23129!/:?]
	at it.unimi.dsi.fastutil.longs.Long2LongOpenHashMap.insert(Long2LongOpenHashMap.java:245) ~[fastutil-8.5.9.jar%23129!/:?]
	at it.unimi.dsi.fastutil.longs.Long2LongOpenHashMap.put(Long2LongOpenHashMap.java:253) ~[fastutil-8.5.9.jar%23129!/:?]
	at net.minecraft.server.level.ChunkMap.m_198874_(ChunkMap.java:799) ~[client-1.20.1-20230612.114412-srg.jar%23206!/:?]
	at it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap$1.forEach(Long2ObjectLinkedOpenHashMap.java:1709) ~[fastutil-8.5.9.jar%23129!/:?]
	at net.minecraft.server.level.ChunkMap.m_140318_(ChunkMap.java:443) ~[client-1.20.1-20230612.114412-srg.jar%23206!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_8419_(ServerChunkCache.java:297) ~[client-1.20.1-20230612.114412-srg.jar%23206!/:?]
	at xaero.map.file.worldsave.WorldDataReader.lambda$buildRegion$1(WorldDataReader.java:149) ~[XaerosWorldMap_1.37.7_Forge_1.20.jar%23204!/:1.37.7]
	at net.minecraft.util.thread.BlockableEventLoop.m_18707_(BlockableEventLoop.java:78) ~[client-1.20.1-20230612.114412-srg.jar%23206!/:?]
	at xaero.map.file.worldsave.WorldDataReader.buildRegion(WorldDataReader.java:149) ~[XaerosWorldMap_1.37.7_Forge_1.20.jar%23204!/:1.37.7]
	at xaero.map.file.worldsave.WorldDataHandler.buildRegion(WorldDataHandler.java:74) ~[XaerosWorldMap_1.37.7_Forge_1.20.jar%23204!/:1.37.7]
	at xaero.map.file.MapSaveLoad.loadRegion(MapSaveLoad.java:759) [XaerosWorldMap_1.37.7_Forge_1.20.jar%23204!/:1.37.7]
	at xaero.map.file.MapSaveLoad.run(MapSaveLoad.java:1006) [XaerosWorldMap_1.37.7_Forge_1.20.jar%23204!/:1.37.7]
	at xaero.map.MapProcessor.run(MapProcessor.java:349) [XaerosWorldMap_1.37.7_Forge_1.20.jar%23204!/:1.37.7]
	at xaero.map.MapRunner.run(MapRunner.java:18) [XaerosWorldMap_1.37.7_Forge_1.20.jar%23204!/:1.37.7]
	at java.lang.Thread.run(Unknown Source) [?:?]
[16:57:09] [Thread-7/INFO]: World map cleaned normally!
[16:57:09] [Render thread/INFO]: World map session finalized.
[16:57:09] [Render thread/INFO]: Minimap session finalized.
[16:57:09] [Render thread/INFO]: JEI StartEventObserver received class net.minecraftforge.client.event.ClientPlayerNetworkEvent$LoggingOut
[16:57:09] [Render thread/INFO]: JEI StartEventObserver transitioning state from ENABLED to DISABLED
[16:57:19] [Render thread/INFO]: Shutting down map thread
```

**Comment by JT122406** [comment]
> Also just for test, try to remove the xaero's map:
> 
> ```
> received server config settings
> [16:57:08] [Render thread/INFO]: Received config from the server: 
> [16:57:08] [Render thread/INFO]: Reloading entity icon resources...
> [16:57:08] [Render thread/INFO]: Done!
> [16:57:09] [Render thread/INFO]: Finalizing world map session...
> [16:57:09] [Thread-7/ERROR]: Region failed to load: (2147483647) 0_0 L0 xaero.map.region.MapRegion@93815cd
> java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 129
> 	at it.unimi.dsi.fastutil.longs.Long2LongOpenHashMap.rehash(Long2LongOpenHashMap.java:1366) ~[fastutil-8.5.9.jar%23129!/:?]
> 	at it.unimi.dsi.fastutil.longs.Long2LongOpenHashMap.insert(Long2LongOpenHashMap.java:245) ~[fastutil-8.5.9.jar%23129!/:?]
> 	at it.unimi.dsi.fastutil.longs.Long2LongOpenHashMap.put(Long2LongOpenHashMap.java:253) ~[fastutil-8.5.9.jar%23129!/:?]
> 	at net.minecraft.server.level.ChunkMap.m_198874_(ChunkMap.java:799) ~[client-1.20.1-20230612.114412-srg.jar%23206!/:?]
> 	at it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap$1.forEach(Long2ObjectLinkedOpenHashMap.java:1709) ~[fastutil-8.5.9.jar%23129!/:?]
> 	at net.minecraft.server.level.ChunkMap.m_140318_(ChunkMap.java:443) ~[client-1.20.1-20230612.114412-srg.jar%23206!/:?]
> 	at net.minecraft.server.level.ServerChunkCache.m_8419_(ServerChunkCache.java:297) ~[client-1.20.1-20230612.114412-srg.jar%23206!/:?]
> 	at xaero.map.file.worldsave.WorldDataReader.lambda$buildRegion$1(WorldDataReader.java:149) ~[XaerosWorldMap_1.37.7_Forge_1.20.jar%23204!/:1.37.7]
> 	at net.minecraft.util.thread.BlockableEventLoop.m_18707_(BlockableEventLoop.java:78) ~[client-1.20.1-20230612.114412-srg.jar%23206!/:?]
> 	at xaero.map.file.worldsave.WorldDataReader.buildRegion(WorldDataReader.java:149) ~[XaerosWorldMap_1.37.7_Forge_1.20.jar%23204!/:1.37.7]
> 	at xaero.map.file.worldsave.WorldDataHandler.buildRegion(WorldDataHandler.java:74) ~[XaerosWorldMap_1.37.7_Forge_1.20.jar%23204!/:1.37.7]
> 	at xaero.map.file.MapSaveLoad.loadRegion(MapSaveLoad.java:759) [XaerosWorldMap_1.37.7_Forge_1.20.jar%23204!/:1.37.7]
> 	at xaero.map.file.MapSaveLoad.run(MapSaveLoad.java:1006) [XaerosWorldMap_1.37.7_Forge_1.20.jar%23204!/:1.37.7]
> 	at xaero.map.MapProcessor.run(MapProcessor.java:349) [XaerosWorldMap_1.37.7_Forge_1.20.jar%23204!/:1.37.7]
> 	at xaero.map.MapRunner.run(MapRunner.java:18) [XaerosWorldMap_1.37.7_Forge_1.20.jar%23204!/:1.37.7]
> 	at java.lang.Thread.run(Unknown Source) [?:?]
> [16:57:09] [Thread-7/INFO]: World map cleaned normally!
> [16:57:09] [Render thread/INFO]: World map session finalized.
> [16:57:09] [Render thread/INFO]: Minimap session finalized.
> [16:57:09] [Render thread/INFO]: JEI StartEventObserver received class net.minecraftforge.client.event.ClientPlayerNetworkEvent$LoggingOut
> [16:57:09] [Render thread/INFO]: JEI StartEventObserver transitioning state from ENABLED to DISABLED
> [16:57:19] [Render thread/INFO]: Shutting down map thread
> ```

Well that is just xero data freaking out because it's missing

**Comment by LaurentCoolen** [comment]
so he launches without Gen's

**Comment by LaurentCoolen** [comment]
I try without the map

**Comment by GuikiPT** [comment]
You created the world from scratch in these new beta version, or you are using some other world that you created in previous versions?

**Comment by LaurentCoolen** [comment]
New world

**Comment by LaurentCoolen** [comment]
Without the map it works

**Comment by GuikiPT** [comment]
With generations?

**Comment by GuikiPT** [comment]
But you are using the generations without the xaero's minimap and is working?

**Comment by LaurentCoolen** [comment]
yes

**Comment by GuikiPT** [comment]
If it is working now without xaero's probally is an xaero's map fault

**Comment by GuikiPT** [comment]
like, for my is working with no problem.

![image](https://github.com/GenerationsMod/Generations-Core/assets/72317733/8a44d826-e32e-4dd5-93ad-014ce4a3c79d)
![image](https://github.com/GenerationsMod/Generations-Core/assets/72317733/a7ef9ba3-2356-424d-8031-9fb08a7a74f6)


If you want the versions that im currently using:
![image](https://github.com/GenerationsMod/Generations-Core/assets/72317733/660dd415-2574-415f-b927-370979adcb40)

**Comment by GuikiPT** [comment]
I would say try to delete the xaero's minimap cache and configs and try again with the latest versions of it. But if the generations is working without it, meanwhile I tested here now and is working with xaero's so I don't know what I have to say, maybe delete the cache and xaero's settings, because that is no longer a generation problem.

**Comment by JT122406** [comment]
Going to close as I assume it has been resolved by current versions if not please open new issue
