### ISSUE TITLE
Generations does not work with the Quark/Zeta mod.

### ISSUE THREAD

**Issue by AlolanXardas** [GenerationsMod/Generations-Core#35]
[generations_and_quark.txt](https://github.com/GenerationsMod/Generations-Core/files/14749491/generations_and_quark.txt)

**Comment by JT122406** [comment]
Can you confirm that cobblemon and Quark works together without gens?

**Comment by AlolanXardas** [comment]
I forgot to add that players cannot connect on the server, and I haven't checked on singleplayer.

The problem appeared after the last major update.

SS:
1. Error after loading the world.
2. Attempt to connect to the server.
3. Mods on the server and client (only required for generations and quark to work).

[22:56:42] [Server thread/ERROR] [zeta/]: Failed to scan recipe generations_core:rks/artcovish. This should be reported to generations_core!
java.lang.RuntimeException: java.lang.NullPointerException: Parameter specified as non-null is null: method com.cobblemon.mod.common.item.PokemonItem$Companion.from, parameter species
at generations.gg.generations.core.generationscore.world.recipe.RksRecipe.m_8043_(RksRecipe.java:88) ~[Generations-Core-Forge-2.3.0-Beta.jar%23110!/:?] {re:classloading}
at org.violetmoon.zeta.util.handler.RecipeCrawlHandler.load(RecipeCrawlHandler.java:98) ~[Zeta-1.0-14.jar%23113!/:1.0-14] {re:classloading}
at org.violetmoon.zeta.util.handler.RecipeCrawlHandler.onTick(RecipeCrawlHandler.java:131) ~[Zeta-1.0-14.jar%23113!/:1.0-14] {re:classloading}
at org.violetmoon.zeta.event.bus.ZetaEventBus$Listeners.doFireNonCancellable(ZetaEventBus.java:242) ~[Zeta-1.0-14.jar%23113!/:1.0-14] {re:classloading}
at org.violetmoon.zeta.event.bus.ZetaEventBus$Listeners.doFire(ZetaEventBus.java:227) ~[Zeta-1.0-14.jar%23113!/:1.0-14] {re:classloading}
at org.violetmoon.zeta.event.bus.ZetaEventBus.fire(ZetaEventBus.java:121) ~[Zeta-1.0-14.jar%23113!/:1.0-14] {re:classloading}
at org.violetmoon.zetaimplforge.ForgeZeta.serverTickStart(ForgeZeta.java:395) ~[Zeta-1.0-14.jar%23113!/:1.0-14] {re:classloading}
at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2352!/:?] {}
at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2352!/:?] {}
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?] {}
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?] {}
at net.minecraftforge.event.ForgeEventFactory.onPreServerTick(ForgeEventFactory.java:945) ~[forge-1.20.1-47.2.0-universal.jar%23120!/:?] {re:classloading}
at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:812) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
at java.lang.Thread.run(Thread.java:833) ~[?:?] {}
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method com.cobblemon.mod.common.item.PokemonItem$Companion.from, parameter species
at com.cobblemon.mod.common.item.PokemonItem$Companion.from(PokemonItem.java) ~[Cobblemon-forge-1.4.1+1.20.1.jar%23109!/:?] {re:classloading}
at com.cobblemon.mod.common.item.PokemonItem.from(PokemonItem.java) ~[Cobblemon-forge-1.4.1+1.20.1.jar%23109!/:?] {re:classloading}
at generations.gg.generations.core.generationscore.world.recipe.RksRecipe.m_8043_(RksRecipe.java:86) ~[Generations-Core-Forge-2.3.0-Beta.jar%23110!/:?] {re:classloading}
... 15 more

![Screenshot_3](https://github.com/GenerationsMod/Generations-Core/assets/39497004/73abbd92-6d32-4e84-93cf-faedd5c2b0bd)
![Screenshot_2](https://github.com/GenerationsMod/Generations-Core/assets/39497004/e12308c5-c468-44ae-be98-5f34f3a9a565)
![Screenshot_1](https://github.com/GenerationsMod/Generations-Core/assets/39497004/c9764621-9807-4028-99df-fd2b0ce9e53a)

**Comment by Waterpicker** [comment]
Quark is trying to grab all the recipes for some reason which includes the ones for the rks machine.

**Comment by Waterpicker** [comment]
wait.

**Comment by ChaosDogG** [comment]
this _might_ have to do with Quark giving the player every recipe upon joining, try turning that feature off in the configs
