### ISSUE TITLE
Missing field IS_FLORAL

### ISSUE THREAD

**Issue by GiuniGiorgio01** [GenerationsMod/Generations-Core#42]
My modpack has only the cobblemon installed with botarium and architectury in order to run the mod but I keep getting this error:

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'generations_core'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchFieldError: IS_FLORAL
	at generations.gg.generations.core.generationscore.fabric.worldgen.GenerationsFabricBiomemodifiers.generateOres(GenerationsFabricBiomemodifiers.java:40)
	at generations.gg.generations.core.generationscore.fabric.GenerationsCoreFabric.onInitialize(GenerationsCoreFabric.java:68)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 6 more

**Comment by JT122406** [comment]
What version of the mod

**Comment by GiuniGiorgio01** [comment]
Cobblemon 1.5.2, I was told that the Generations-Core is not yet compatible with the latest version of the cobblemon, so maybe this is why I get the error
