### ISSUE TITLE
fails to show models on unix (log from linux)

### ISSUE THREAD

**Issue by OrdinaryCloverOC** [GenerationsMod/Generations-Core#52]
```
[23:32:36] [Render thread/INFO]: New world map session initialized!
[23:32:36] [Render thread/INFO]: Started 2 worker threads
[23:32:36] [Render thread/INFO]: Received config from the server: 
[23:32:36] [REI-ReloadPlugins/INFO]: [REI] ========================================
[23:32:36] [REI-ReloadPlugins/INFO]: [REI] REIPlugin starting main-reload for START.
[23:32:36] [REI-ReloadPlugins/INFO]: [REI] Plugins (8):
[23:32:36] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultClientPlugin of DefaultClientPlugin [roughlyenoughitems]
[23:32:36] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultPlugin of DefaultPlugin [roughlyenoughitems]
[23:32:36] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) FabricFluidAPISupportPlugin
[23:32:36] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) HideIngredientsFromTagsPlugin of HideIngredientsFromTagsPlugin [roughlyenoughitems]
[23:32:36] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems]
[23:32:36] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) ReiCompatClient of ReiCompatClient [generations_core]
[23:32:36] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) REITooltipPlugin of REITooltipPlugin [appleskin]
[23:32:36] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[23:32:36] [REI-ReloadPlugins/INFO]: [REI] ========================================
[23:32:36] [Render thread/WARN]: Result for RKS machine recipe generations_core:rks/ironthreads is missing.
[23:32:36] [REI-ReloadPlugins/INFO]: [REI] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[23:32:36] [REI-ReloadPlugins/INFO]: [REI] REIClientPlugin starting main-reload for START.
[23:32:36] [REI-ReloadPlugins/INFO]: [REI] Plugins (5):
[23:32:36] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultClientPlugin of DefaultClientPlugin [roughlyenoughitems]
[23:32:36] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) HideIngredientsFromTagsPlugin of HideIngredientsFromTagsPlugin [roughlyenoughitems]
[23:32:36] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems]
[23:32:36] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) ReiCompatClient of ReiCompatClient [generations_core]
[23:32:36] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) REITooltipPlugin of REITooltipPlugin [appleskin]
[23:32:36] [REI-ReloadPlugins/INFO]: [REI] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[23:32:37] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2288ms or 45 ticks behind
[23:32:37] [Render thread/WARN]: Result for RKS machine recipe generations_core:rks/ironthreads is missing.
[23:32:37] [Render thread/WARN]: [REI] Found 1 existing reload task(s) after trying to terminate them!
[23:32:37] [Render thread/INFO]: Loading all registered leaf blocks.
[23:32:37] [Render thread/INFO]: Minimap updated server level id: -2102101049 for world ResourceKey[minecraft:dimension / minecraft:overworld]
[23:32:37] [REI-ReloadPlugins/INFO]: [REI] ****************************************
[23:32:37] [REI-ReloadPlugins/INFO]: [REI] REIServerPlugin starting main-reload for START.
[23:32:37] [REI-ReloadPlugins/INFO]: [REI] Plugins (3):
[23:32:37] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultPlugin of DefaultPlugin [roughlyenoughitems]
[23:32:37] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) FabricFluidAPISupportPlugin
[23:32:37] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[23:32:37] [REI-ReloadPlugins/INFO]: [REI] ****************************************
[23:32:37] [REI-ReloadPlugins/INFO]: [REI] REIPlugin finished post-reload for START in 10.93 ms, totaling 162.3 ms.
[23:32:37] [REI-ReloadPlugins/INFO]: [REI] REIClientPlugin finished post-reload for START in 3.798 ms, totaling 1.193 s.
[23:32:37] [REI-ReloadPlugins/INFO]: [REI] REIServerPlugin finished post-reload for START in 1.472 ms, totaling 15.42 ms.
[23:32:37] [REI-ReloadPlugins/INFO]: [REI] ----------------------------------------
[23:32:37] [REI-ReloadPlugins/INFO]: [REI] REIPlugin starting main-reload for END.
[23:32:37] [REI-ReloadPlugins/INFO]: [REI] Plugins (8):
[23:32:37] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultClientPlugin of DefaultClientPlugin [roughlyenoughitems]
[23:32:37] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultPlugin of DefaultPlugin [roughlyenoughitems]
[23:32:37] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) FabricFluidAPISupportPlugin
[23:32:37] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) HideIngredientsFromTagsPlugin of HideIngredientsFromTagsPlugin [roughlyenoughitems]
[23:32:37] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems]
[23:32:37] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) ReiCompatClient of ReiCompatClient [generations_core]
[23:32:37] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) REITooltipPlugin of REITooltipPlugin [appleskin]
[23:32:37] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[23:32:37] [REI-ReloadPlugins/INFO]: [REI] ----------------------------------------
[23:32:38] [REI-ReloadPlugins/INFO]: [REI] ----------------------------------------
[23:32:38] [REI-ReloadPlugins/INFO]: [REI] REIClientPlugin starting main-reload for END.
[23:32:38] [REI-ReloadPlugins/INFO]: [REI] Plugins (5):
[23:32:38] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultClientPlugin of DefaultClientPlugin [roughlyenoughitems]
[23:32:38] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) HideIngredientsFromTagsPlugin of HideIngredientsFromTagsPlugin [roughlyenoughitems]
[23:32:38] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems]
[23:32:38] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) ReiCompatClient of ReiCompatClient [generations_core]
[23:32:38] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) REITooltipPlugin of REITooltipPlugin [appleskin]
[23:32:38] [REI-ReloadPlugins/INFO]: [REI] ----------------------------------------
[23:32:39] [Render thread/ERROR]: Error executing task on Client
io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1454) ~[netty-buffer-4.1.82.Final.jar:?]
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1440) ~[netty-buffer-4.1.82.Final.jar:?]
	at io.netty.buffer.AbstractByteBuf.readIntLE(AbstractByteBuf.java:817) ~[netty-buffer-4.1.82.Final.jar:?]
	at net.minecraft.class_2540.readIntLE(class_2540.java:1358) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.readIntLE(class_2540.java:1358) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.readIntLE(class_2540.java:1358) ~[client-intermediary.jar:?]
	at io.github.thecsdev.betterstats.client.network.BetterStatsClientPlayNetworkHandler.onIHaveBss(BetterStatsClientPlayNetworkHandler.java:128) ~[betterstats-3.12.6+fabric-1.20.1.jar:?]
	at io.github.thecsdev.betterstats.network.BetterStatsNetwork.lambda$static$6(BetterStatsNetwork.java:69) ~[betterstats-3.12.6+fabric-1.20.1.jar:?]
	at net.minecraft.class_2658.mdd110c6$tcdcommons$lambda$tcdcommons_onApply$0$1(class_2658.java:1047) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1175) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.5.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
[23:32:39] [Render thread/INFO]: Loaded 2 advancements
[23:32:40] [Render thread/INFO]: Reloading entity icon resources...
[23:32:40] [Render thread/INFO]: Reloaded entity icon resources!
[23:32:40] [REI-ReloadPlugins/WARN]: Result for RKS machine recipe generations_core:rks/ironthreads is missing.
[23:32:41] [REI-ReloadPlugins/INFO]: [STDOUT]: Finalizing fluid item registration
[23:32:41] [Render thread/INFO]: Loaded 3 advancements
[23:32:41] [REI-ReloadPlugins/INFO]: [REI] ========================================
[23:32:41] [REI-ReloadPlugins/INFO]: [REI] REIServerPlugin starting main-reload for END.
[23:32:41] [REI-ReloadPlugins/INFO]: [REI] Plugins (3):
[23:32:41] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultPlugin of DefaultPlugin [roughlyenoughitems]
[23:32:41] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) FabricFluidAPISupportPlugin
[23:32:41] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[23:32:41] [REI-ReloadPlugins/INFO]: [REI] ========================================
[23:32:41] [REI-ReloadPlugins/INFO]: [REI] REIPlugin finished post-reload for END in 5.252 ms, totaling 126.5 ms.
[23:32:41] [REI-ReloadPlugins/INFO]: [REI] REIClientPlugin finished post-reload for END in 3.295 ms, totaling 3.747 s.
[23:32:41] [REI-ReloadPlugins/INFO]: [REI] REIServerPlugin finished post-reload for END in 598.4 μs, totaling 27.87 ms.
[23:32:47] [Render thread/INFO]: [System] [CHAT] Hello, thank you for downloading Terralith!\n\n- Stardust Labs Discord (for Terralith)\n- Bisect Hosting (our server hosting partner)\n- Disable this message (mod/datapack)\n 
[23:32:48] [CraftPresence/ERROR]: Unable to connect to Discord...
[23:32:54] [Server thread/INFO]: Saving and pausing game...
[23:32:54] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[23:32:54] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[23:32:54] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[23:32:55] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 3032ms or 60 ticks behind
[23:32:59] [Server thread/INFO]: [player] has made the advancement [The World of Cobblemon!]
[23:32:59] [Render thread/INFO]: [System] [CHAT] [player] has made the advancement [The World of Cobblemon!]
[23:32:59] [Render thread/INFO]: Loaded 16 advancements
[23:33:03] [Thread-7/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[23:33:03] [Thread-7/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[23:33:03] [Thread-7/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[23:33:03] [Thread-7/ERROR]: Uncaught exception in thread "Thread-7"
java.lang.UnsatisfiedLinkError: Failed to locate library: libdraco.so
	at org.lwjgl.system.Library.loadNative(Library.java:327) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.system.Library.loadNative(Library.java:224) ~[lwjgl-3.3.1.jar:?]
	at gg.generations.rarecandy.assimp.Assimp.<clinit>(Assimp.java:171) ~[Generations-Core-fabric-4.0.0-Beta-SNAPSHOT.jar:?]
	at gg.generations.rarecandy.renderer.loading.ModelLoader.read(ModelLoader.java:679) ~[Generations-Core-fabric-4.0.0-Beta-SNAPSHOT.jar:?]
	at gg.generations.rarecandy.renderer.loading.ModelLoader.create2(ModelLoader.java:74) ~[Generations-Core-fabric-4.0.0-Beta-SNAPSHOT.jar:?]
	at generations.gg.generations.core.generationscore.common.client.render.rarecandy.loading.GenerationsModelLoader.lambda$compiledModelMethod$1(GenerationsModelLoader.java:30) ~[Generations-Core-fabric-4.0.0-Beta-SNAPSHOT.jar:?]
	at gg.generations.rarecandy.renderer.loading.ModelLoader.lambda$threadedCreateObject$25(ModelLoader.java:614) ~[Generations-Core-fabric-4.0.0-Beta-SNAPSHOT.jar:?]
	at gg.generations.rarecandy.renderer.ThreadSafety.lambda$wrapException$1(ThreadSafety.java:24) ~[Generations-Core-fabric-4.0.0-Beta-SNAPSHOT.jar:?]
	at gg.generations.rarecandy.renderer.loading.ModelLoader.createObject(ModelLoader.java:561) ~[Generations-Core-fabric-4.0.0-Beta-SNAPSHOT.jar:?]
	at gg.generations.rarecandy.renderer.loading.ModelLoader.createObject(ModelLoader.java:555) ~[Generations-Core-fabric-4.0.0-Beta-SNAPSHOT.jar:?]
	at generations.gg.generations.core.generationscore.common.client.render.rarecandy.loading.GenerationsModelLoader.compiledModelMethod(GenerationsModelLoader.java:25) ~[Generations-Core-fabric-4.0.0-Beta-SNAPSHOT.jar:?]
	at generations.gg.generations.core.generationscore.common.client.render.rarecandy.CompiledModel._init_$lambda$0(CompiledModel.kt:40) ~[Generations-Core-fabric-4.0.0-Beta-SNAPSHOT.jar:?]
	at generations.gg.generations.core.generationscore.common.util.TaskQueue.processTasks(TaskQueue.java:27) ~[Generations-Core-fabric-4.0.0-Beta-SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```
if you need the whole log lmk. (zero shaders, zero additional resource packs, tested with/without iris)

**Comment by OrdinaryCloverOC** [comment]
![gen1](https://github.com/user-attachments/assets/0f5cbe93-5579-425f-bd74-1f11aa428f74)
![gen2](https://github.com/user-attachments/assets/f5c79fdb-83c3-478e-9758-e92faabdee1e)
![gen3](https://github.com/user-attachments/assets/4bbc274b-bf40-4b55-9b71-3b386968118a)

**Comment by OrdinaryCloverOC** [comment]
i'm pretty sure this was fixed ages ago. was the repo moved somewhere else?

**Comment by Waterpicker** [comment]
> i'm pretty sure this was fixed ages ago. was the repo moved somewhere else?

Nope. Just never closed it. Closing it now.
